// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARX8CdAVum8K4_kUuX2hzGpZF0wJUWYI8',
    appId: '1:90709939017:web:2f6920bce1aacc7f034098',
    messagingSenderId: '90709939017',
    projectId: 'managemate-7939b',
    authDomain: 'managemate-7939b.firebaseapp.com',
    storageBucket: 'managemate-7939b.firebasestorage.app',
    measurementId: 'G-69B1VPYV2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnRYJlDRus79XS1HdyPdeO-03SzZ0mxBw',
    appId: '1:90709939017:android:7758491962e265b9034098',
    messagingSenderId: '90709939017',
    projectId: 'managemate-7939b',
    storageBucket: 'managemate-7939b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCTjHHEBk4zPmrDj8mYHWtgLofWs-KUo8',
    appId: '1:90709939017:ios:0b0469b559e46ef0034098',
    messagingSenderId: '90709939017',
    projectId: 'managemate-7939b',
    storageBucket: 'managemate-7939b.firebasestorage.app',
    iosBundleId: 'com.example.teamtasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCTjHHEBk4zPmrDj8mYHWtgLofWs-KUo8',
    appId: '1:90709939017:ios:0b0469b559e46ef0034098',
    messagingSenderId: '90709939017',
    projectId: 'managemate-7939b',
    storageBucket: 'managemate-7939b.firebasestorage.app',
    iosBundleId: 'com.example.teamtasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARX8CdAVum8K4_kUuX2hzGpZF0wJUWYI8',
    appId: '1:90709939017:web:f7212b65d700dca1034098',
    messagingSenderId: '90709939017',
    projectId: 'managemate-7939b',
    authDomain: 'managemate-7939b.firebaseapp.com',
    storageBucket: 'managemate-7939b.firebasestorage.app',
    measurementId: 'G-VE0PTS8QG5',
  );
}
